kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-deploymentkind: Service
2
apiVersion: v1
3
metadata:
4
  name: train-schedule-service
5
spec:
6
  type: NodePort
7
  selector:
8
    app: train-schedule
9
  ports:
10
  - protocol: TCP
11
    port: 8080
12
    nodePort: 8080
13
​
14
---
15
​
16
apiVersion: extensions/v1beta1
17
kind: Deployment
18
metadata:
19
  name: train-schedule-deployment
20
  labels:
21
    app: train-schedule
22
spec:
23
  replicas: 2
24
  selector:
25
    matchLabels:
26
      app: train-schedule
27
  template:
28
    metadata:
29
      labels:
30
        app: train-schedule
31
    spec:
32
      containers:
33
      - name: train-schedule
34
        image: linuxacademycontent/train-schedule:autoscaling
35
        ports:
36
        - containerPort: 8080
37
        livenessProbe:
38
          httpGet:
39
            path: /
40
            port: 8080
41
          initialDelaySeconds: 15
42
          timeoutSeconds: 1
43
          periodSeconds: 10
44

  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: linuxacademycontent/train-schedule:autoscaling
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: train-schedule
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: train-schedule-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
